# Hugo internal
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "http://EveryRealm.io/"
languageCode = "en-us"
theme = "Panyon"

# Hugo internal extras
pygmentsuseclasses = "true"
disqusShortname = "Panarchus"
googleAnalytics = "UA-74040307-1"

[permalinks]
    post = "/:section/:slug"

[params]
    Author = "Panarchus"
    bio = "Budding Everyman"
    location = "Neo-England"
    site_description = "intersection of things"

    # Format dates with Go's time formatting
    DateForm = "2006-01-02"
    Title = "Every Realm"
    Tagline = "intersection of things"

    # footnote default superscript
    fnote_def = "[Editor's Note]"

    # Twitter handle
    twitter_handle = "panarchus"

[params.style]
    background = "/assets/mochaGrunge.png"
    theme = "theme-pan-stardust"

[params.github]
    url = "http://github.com/panarchus"
    head = "master"

# Things to appear in sidebar (weight determines order)
# Note: add slash at end to allow highlighting when on the same page
[params.sidebar]
    [params.sidebar.Blog]
        url = "/post/"
        title = "Blog"
        weight = "3"
    [params.sidebar.About]
        url = "/about/"
        title = "About"
        weight = "2"
    [params.sidebar.Home]
        url = "/"
        title = "Home"
        weight = "1"
